---
# tasks file for create_instance
- name: Launch RHEL instance
  ec2:
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    keypair: "{{ keypair }}"
    instance_tags: "{{ item }}"
    group: "{{ security_group }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    region: "{{ region }}"
    wait: true
    assign_public_ip: yes
  register: ec2_info
  with_items:
    - "{{ instance_tags }}"

#- debug:
#    msg: "{{ item.instances[0].public_ip }}"
#  with_items: "{{ ec2_info.results }}"

- name: Wait for SSH
  wait_for:
    state: started
    port: 22
    host: "{{ item.instances[0].public_ip }}"
  with_items: "{{ ec2_info.results }}"

- name: Add ip to group
  add_host:
     name: "{{ item.instances[0].public_ip }}"
     groups: "{{ group_name }}"
  with_items: "{{ ec2_info.results }}"

- name: Set_fact instance_list
  set_fact:
    instance_list: "{{ instance_list }} + ['{{ ec2_info.results[0].instance_ids[0] }}']"
